"use client";
import { useRef, useState } from "react";
import styles from "./ReportDownload.module.css";

export default function ReportDownload({ config, metrics, breakdown, projector, room }) {
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  const handleDownload = async () => {
    setLoading(true);
    setDone(false);

    try {
      const { jsPDF } = await import("jspdf");

      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageW = 210;
      const pageH = 297;
      const margin = 18;
      let y = margin;

      // Helper shortcuts
      const line = (x1, y1, x2, y2, col = [200, 210, 230]) => {
        doc.setDrawColor(...col);
        doc.line(x1, y1, x2, y2);
      };
      const rect = (x, yy, w, h, col) => {
        doc.setFillColor(...col);
        doc.rect(x, yy, w, h, "F");
      };

      // ─── Header banner ─────────────────────────────────────────────
      rect(0, 0, pageW, 32, [0, 65, 172]);
      rect(0, 28, pageW, 6, [0, 163, 224]);

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("EPSON Classroom Visibility Report", margin, 13);

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text("Board-ready summary · Generated by Epson Classroom Simulator", margin, 21);

      const dateStr = new Date().toLocaleDateString("en-GB", {
        day: "numeric", month: "long", year: "numeric",
      });
      doc.text(dateStr, pageW - margin, 21, { align: "right" });

      y = 42;

      // ─── Classroom Configuration ────────────────────────────────────
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 65, 172);
      doc.text("Classroom Configuration", margin, y);
      y += 5;
      line(margin, y, pageW - margin, y, [0, 163, 224]);
      y += 6;

      const configRows = [
        ["Room Size", room ? `${room.label} (${room.width}m × ${room.depth}m)` : "None"],
        ["Projector Model", projector ? `${projector.name} (${projector.subtitle})` : "None"],
        ["Screen Size", `${config.screenSize}" diagonal`],
        ["Projector Brightness", projector ? `${projector.lumens.toLocaleString()} lumens` : "None"],
        ["Projector Resolution", projector?.resolution ?? "None"],
        ["Throw Type", projector?.type ?? "None"],
      ];

      doc.setFontSize(9);
      configRows.forEach(([label, val], i) => {
        const rowY = y + i * 7;
        if (i % 2 === 0) {
          rect(margin, rowY - 3, pageW - margin * 2, 7, [245, 248, 255]);
        }
        doc.setFont("helvetica", "bold");
        doc.setTextColor(60, 70, 100);
        doc.text(label, margin + 2, rowY + 2);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(20, 30, 60);
        doc.text(val, margin + 55, rowY + 2);
      });

      y += configRows.length * 7 + 10;

      // ─── Key Metrics ─────────────────────────────────────────────────
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 65, 172);
      doc.text("Key Metrics", margin, y);
      y += 5;
      line(margin, y, pageW - margin, y, [0, 163, 224]);
      y += 8;

      const metricDefs = [
        {
          key: "visibilityCoverage",
          label: "Visibility Coverage",
          suffix: "%",
          desc: "Seats with a clear, usable view of the screen",
          color: metrics?.visibilityCoverage >= 80 ? [26, 122, 74] : metrics?.visibilityCoverage >= 60 ? [196, 124, 18] : [139, 26, 26],
        },
        {
          key: "engagementRisk",
          label: "Engagement Risk",
          suffix: "%",
          desc: "Seats where visibility is compromised",
          color: metrics?.engagementRisk <= 20 ? [26, 122, 74] : metrics?.engagementRisk <= 40 ? [196, 124, 18] : [139, 26, 26],
        },
        {
          key: "equityIndex",
          label: "Equity Index",
          suffix: "/100",
          desc: "Overall fairness of seat quality distribution",
          color: metrics?.equityIndex >= 75 ? [26, 122, 74] : metrics?.equityIndex >= 50 ? [196, 124, 18] : [139, 26, 26],
        },
      ];

      const colW = (pageW - margin * 2 - 8) / 3;
      metricDefs.forEach((m, i) => {
        const x = margin + i * (colW + 4);
        const val = metrics?.[m.key] ?? 0;

        // Card bg
        rect(x, y, colW, 36, [240, 245, 255]);
        // Color bar top
        rect(x, y, colW, 3, m.color);

        // Value
        doc.setFontSize(24);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...m.color);
        doc.text(`${val}${m.suffix}`, x + colW / 2, y + 16, { align: "center" });

        // Label
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(40, 50, 90);
        doc.text(m.label, x + colW / 2, y + 24, { align: "center" });

        // Desc
        doc.setFontSize(7);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 110, 140);
        const lines = doc.splitTextToSize(m.desc, colW - 4);
        doc.text(lines, x + colW / 2, y + 30, { align: "center" });
      });

      y += 44;

      // ─── Zone Breakdown ────────────────────────────────────────────
      if (breakdown) {
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 65, 172);
        doc.text("Seat Zone Breakdown", margin, y);
        y += 5;
        line(margin, y, pageW - margin, y, [0, 163, 224]);
        y += 7;

        const zoneData = [
          { key: "analytical", label: "Clear viewing", color: [34, 197, 94], desc: "Ideal for reading text & detail" },
          { key: "basic",      label: "Basic viewing",      color: [245, 158, 11],  desc: "Good for presentations" },
          { key: "passive",    label: "Passive/limited viewing",    color: [239, 68, 68], desc: "Suitable for video content only" },
          { key: "unviewable", label: "Out of range",       color: [229, 231, 235],  desc: "Too far for effective learning" },
        ];

        const barW = pageW - margin * 2;
        const total = breakdown.total || 1;

        // Stacked bar
        let barX = margin;
        zoneData.forEach(({ key, color }) => {
          const count = breakdown[key] ?? 0;
          const segW = (count / total) * barW;
          if (segW > 0) {
            rect(barX, y, segW, 8, color);
            barX += segW;
          }
        });
        y += 13;

        // Zone legend table
        doc.setFontSize(9);
        zoneData.forEach(({ key, label, color, desc }, i) => {
          const count = breakdown[key] ?? 0;
          const pct = Math.round((count / total) * 100);
          const rowY = y + i * 8;

          if (i % 2 === 0) rect(margin, rowY - 2, barW, 8, [245, 248, 255]);

          // Colour swatch
          rect(margin + 2, rowY, 6, 5, color);

          doc.setFont("helvetica", "bold");
          doc.setTextColor(30, 40, 80);
          doc.text(label, margin + 12, rowY + 4);

          doc.setFont("helvetica", "normal");
          doc.setTextColor(80, 90, 120);
          doc.text(desc, margin + 65, rowY + 4);

          doc.setFont("helvetica", "bold");
          doc.setTextColor(0, 65, 172);
          doc.text(`${count} seats (${pct}%)`, pageW - margin, rowY + 4, { align: "right" });
        });

        y += zoneData.length * 8 + 10;
      }

      // ─── 4/6/8 Rule Explanation ────────────────────────────────────
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 65, 172);
      doc.text("About the 4/6/8 Viewing Rule", margin, y);
      y += 5;
      line(margin, y, pageW - margin, y, [0, 163, 224]);
      y += 7;

      const explanation = [
        "The 4/6/8 rule is the industry-standard framework for determining optimal display sizing in educational environments.",
        "• Clear viewing (×4): For reading fine text and detailed information. Distance ≤ 4× screen height.",
        "• Basic viewing (×6): For standard presentations and slideshows. Distance ≤ 6× screen height.",
        "• Passive/limited viewing (×8): Acceptable for video and movie content. Distance ≤ 8× screen height.",
        "• Out of range (Beyond ×8): Considered out of range for effective educational purposes.",
      ];

      doc.setFontSize(8.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40, 50, 90);
      explanation.forEach((line_) => {
        const lines = doc.splitTextToSize(line_, pageW - margin * 2);
        doc.text(lines, margin, y);
        y += lines.length * 5 + 1;
      });

      // ─── Footer ───────────────────────────────────────────────────
      rect(0, pageH - 16, pageW, 16, [0, 65, 172]);
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.text("Generated by Epson Classroom Simulator · epson.co.uk/education", margin, pageH - 6);
      doc.text(`Page 1 of 1`, pageW - margin, pageH - 6, { align: "right" });

      // Save
      doc.save(`epson-classroom-report-${Date.now()}.pdf`);
      setDone(true);
      setTimeout(() => setDone(false), 3000);
    } catch (err) {
      console.error("PDF generation failed:", err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.wrapper}>
      <div className={styles.info}>
        <div>
          <div className={styles.title}>Download Board Report</div>
          <div className={styles.desc}>
            Export a professional PDF summary of your classroom simulation, ideal for budget approvals and stakeholder presentations.
          </div>
        </div>
      </div>
      <button
        id="download-report"
        className={`btn btn-primary ${styles.downloadBtn}`}
        onClick={handleDownload}
        disabled={loading}
      >
        {loading ? (
          <>
            <span className={styles.spinner} />
            Generating…
          </>
        ) : done ? (
          <>Report Downloaded</>
        ) : (
          <>
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path d="M8 1v9M5 7l3 3 3-3M2 11v1a2 2 0 002 2h8a2 2 0 002-2v-1"
                stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            Download PDF Report
          </>
        )}
      </button>
    </div>
  );
}
